## Exercise 1: Solving the Empirical Distribution

For the empirical model, we assign a distinct parameter to each feature subgroup:
* **Parameters:** $\theta = (p_{1|00}, p_{1|01}, p_{1|10}, p_{1|11})$
* **Model:** $\hat{p}_\theta(1 | x_0, x_1) = p_{1|x_0 x_1}$

Let $S_{ij}$ be the set of $N_{ij}$ patients with features $x_0=i$ and $x_1=j$. The global negative log-likelihood decouples into independent sums for each subgroup:

$$
\ell_{ij}(p_{1|ij}) = - \sum_{n \in S_{ij}} \Big[ y_n \log(p_{1|ij}) + (1-y_n) \log(1 - p_{1|ij}) \Big]
$$

Show analytically that MLE is solved by

$$
\hat{p}_{1|ij} = \frac{1}{N_{ij}} \sum_{n \in S_{ij}} y_n
$$

### Solution

## Computational: Empirical distribution MLE for health insurance claims prediction (*)

Write python or R code to compute maximum likelihood estimates for predicting big claims based on data samples at [../notebooks/data/big-claim-events.csv](../notebooks/data/big-claim-events.csv)

Comment on the results.

### Solution

In [1]:
from pathlib import Path
import os

import pandas as pd

In [2]:
data_dir = Path(os.getcwd()) / 'data'
big_claim_events_df = pd.read_csv(data_dir / 'big-claim-events.csv')
print('Sample values:')
big_claim_events_df.head()

Sample values:

   customer_id  year  skin_cancer  depression  big_claim
0            0  2022          0.0         0.0          1
1            1  2022          0.0         0.0          1
2            2  2022          0.0         0.0          1
3            3  2022          0.0         0.0          1
4            4  2022          0.0         0.0          1

In [3]:
big_claim_events_df.tail()

      customer_id  year  skin_cancer  depression  big_claim
2503          831  2024          0.0         0.0          1
2504          832  2024          0.0         0.0          1
2505          833  2024          1.0         0.0          0
2506          834  2024          0.0         0.0          1
2507          835  2024          1.0         0.0          1

In [4]:
# Or, using polars like the cool kids
# import polars as pl

# big_claim_events_df = pl.read_csv(data_dir / 'big-claim-events.csv')
# big_claim_events_df.head()

## Train, validation and test sets for MLE, empirical distribution (*)

Since there are no hyperparameters to choose for the empirical distribution model, we combine train and validation datasets.

Calculate the empirical MLE model for the train-validation set of records from 2022 and 2023, and compare to a test set of records from 2024.

### Solution

## Bootstrap statistics on the train-validation set for MLE, empirical distribution (**)

Use [empirical bootstrapping](https://en.wikipedia.org/wiki/Bootstrapping_(statistics)) to estimate the mean MLE parameters and their standard deviations on the train-validation set from above.